remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_jaxrs_v2_1]
description: [Oracle Technology Compatibility Kit User's Guide for Java API for RESTful Web Services (JAX-RS) 2.1 for Technology Licensees, Release 2.1]

# sidebar links url
links:
  source: https://github.com/javaee/tck_jaxrs_v2_1
  download: https://github.com/javaee/tck_jaxrs_v2_1/releases
  #mailinglist: https://javaee.groups.io/g/tck_jaxrs_v2_1
  #javadocs:
  docs: https://javaee.github.io/tck_jaxrs_v2_1
  #faq:

