type=page
status=published
title=Setup and Configuration
next=using.html
prev=install.html
~~~~~~
include::attributes.conf[]
Setup and Configuration
=======================

[[GBFVV]]



[[setup-and-configuration]]
4 Setup and Configuration
-------------------------


[NOTE]
====
The Jakarta EE Specification process provides for any number of compatible implementations.
As additional implementations become available, refer to project or product documentation from
those vendors for specific TCK setup and operational guidance.

====

This chapter describes how to set up the {TechnologyShortName} TCK and
JavaTest harness software. Before proceeding with the instructions in
this chapter, be sure to install all required software, as described in
link:install.html#GBFTP[Chapter 3, "Installation."]

After completing the instructions in this chapter, proceed to
link:using.html#GBFWO[Chapter 5, "Executing Tests,"] for instructions on
running the {TechnologyShortName} TCK.

include::config.inc[]
