.  Install the Jakarta EE {JakartaEEVersion} CI software, for example {TechnologyRI} (which hosts the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} CI), if it is not already
installed. +
.  Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} CI used for running the
{TechnologyShortName} TCK {TechnologyVersion}. For example you could use {TechnologyRI}.
This software may be obtained from {TechnologyRIURL}.
