////
NOTE TO WRITERS:
Steps to install the Jakarta EE Compatible Implementation.
For standalone technologies, no server may be required, and the
below lines can be removed.
This is used in install.adoc in section 3.2.
////
.  Install the Jakarta EE 10 CI software (the servlet Web container used
for running the {TechnologyShortName} TCK with the
{TechnologyShortName} {TechnologyVersion} CI), if it is not already
installed. +
Download and install the Servlet Web container with the
{TechnologyShortName} {TechnologyVersion} CI used for running the
{TechnologyShortName} TCK {TechnologyVersion}, represented by the Jakarta
EE 10 CI.
If you intend to use {TechnologyRI}, you may obtain this software via the
downloads tab from the project website: {TechnologyRIURL}.
